refactor: increment prop colorVariant this component and refactor component
platformbuilders/fluid-react-native pull request #151
Opened 2024-05-06 20:23 UTC by gabrielRochaBuilders

refactor: increment prop colorVariant this component and refactor component

## O que foi feito? 📝

Foi inserido uma nova prop no componente de button, para que possamos alterar entre variante e colorVariante, assim cada uma tem uma responsabilidade.
**variant**: ficou responsável por gerenciar o "tipo de botão" =>  'filled', 'ghost', 'tint', 'outline', 'flat'
**colorVariant**: ficou responsável por gerenciar a "cor do botão " =>  'primary', 'secondary', 'accent', 'danger', 'success', 'warning', 'info',

foi incrementado estas possibilidade no storyBook, para que possamos deixar o componente o mais fiel possivel

## Screenshots ou GIFs 📸

https://github.com/platformbuilders/fluid-react-native/assets/167531818/9dad8876-fb66-402a-a554-c46a8aa66dc9

## Tipo de mudança 🏗

- [ ] Nova feature (mudança non-breaking que adiciona uma funcionalidade)
- [ ] Bug fix (mudança non-breaking que conserta um problema)
- [x ] Refactor (mudança non-breaking que melhora o código ou débito técnico)
- [ ] Chore (nenhuma das anteriores, como upgrade de libs)
- [x] Breaking change 🚨

## Checklist 🧐

- [ ] Testado no iOS
- [ x] Testado no Android

2024-05-06 20:52 UTC, mdlucas requested changes

2024-05-06 20:52 UTC, mdlucas commented on src/theme/theme.json
> +        "value": "#1a75ff",
remover alterações do tema

2024-05-06 20:52 UTC, mdlucas commented on src/components/Button/index.tsx
> +        hasBorder={hasBorder || variant === 'outline'}
acho que agora nao precisamos mais da prop "hasBorder", podemos validar pelo tipo do botao, exibir a bordar se for outline

2024-05-07 12:07 UTC, gabrielRochaBuilders commented on src/theme/theme.json
> +        "value": "#1a75ff",
Perfeito, estou subindo essa remoção do thema e ajustando os testes

2024-05-07 12:08 UTC, marcelxsilva commented on src/components/Button/styles.ts
> +  switch (props.colorVariant) {
A mesma coisa do comentario anterior aqui.

2024-05-07 12:08 UTC, marcelxsilva commented on src/components/Button/styles.ts
> +  if (
A mesma coisa do comentario anterior aqui.

2024-05-07 12:18 UTC, mdlucas commented on src/components/Button/styles.ts
> +  switch (props.colorVariant) {
@marcelxsilva acho que nesse tem que ter o switch aqui pra validar a variant da cor, se colocar dentro do style nao vai legivel

2024-05-07 19:13 UTC, marcelxsilva approved these changes

2024-05-07 19:13 UTC, mdlucas approved these changes

2024-05-07 19:13 UTC, merged