Chore/update react version
platformbuilders/fluid-react-native pull request #95
Opened 2022-09-28 16:32 UTC by lineubuilders

## O que foi feito? 📝

- Atualizei a versão do `react` e `react-test-renderer` para a versão `18.2.0`;
- Atualizei os snapshots.

## Screenshots ou GIFs 📸

![Screenshot_1664382291](https://user-images.githubusercontent.com/91978378/192835928-f24c2f7b-b6e7-49fe-aae4-f2fcdce0f212.png)
![Screen Shot 2022-09-28 at 13 25 27](https://user-images.githubusercontent.com/91978378/192835920-7a675760-23a3-4588-8187-e49a156024ca.png)

## Tipo de mudança 🏗

- [ ] Nova feature (mudança non-breaking que adiciona uma funcionalidade)
- [ ] Bug fix (mudança non-breaking que conserta um problema)
- [ ] Refactor (mudança non-breaking que melhora o código ou débito técnico)
- [x] Chore (nenhuma das anteriores, como upgrade de libs)
- [ ] Breaking change 🚨

## Checklist 🧐

- [x] Testado no iOS
- [x] Testado no Android

2022-09-28 16:41 UTC, edutoledoo approved these changes

2022-09-28 16:41 UTC, meycon1 requested changes

2022-09-28 16:41 UTC, meycon1 commented on src/components/Markdown/index.tsx
> +import React, { ReactNode } from 'react';
Não seria melhor chamar o PropsWithChildren e envolver o `PropsWithChildren<Props>>`?

2022-09-28 16:44 UTC, lineubuilders commented on src/components/Markdown/index.tsx
> +import React, { ReactNode } from 'react';
O mais comum que eu vejo é sempre passar o children dentro das Props e tipar usando o ReactNode. Até dentro do projeto tem alguns pontos assim, usando o `PropsWithChildren<Props>>` acho que iria sair um pouco do padrão que já existe

2022-09-28 16:45 UTC, edutoledoo commented on src/components/Markdown/index.tsx
> +import React, { ReactNode } from 'react';
Sim!
Com o FC tbm caso necessário:
`FC <PropsWithChildren<Props>> `

2022-09-28 16:51 UTC, lineubuilders commented on src/components/Markdown/index.tsx
> +import React, { ReactNode } from 'react';
Agora ficou confuso hahaha. Com ou sem o `PropsWithChildren<Props>>`?

@edutoledoo @meycon1

2022-09-28 16:56 UTC, meycon1 commented on src/components/Markdown/index.tsx
> +import React, { ReactNode } from 'react';
Então eu acho que para evitar da manutenção em todo o código que utiliza o children ter que passar o Node é rium, vai dar muito trabalho fazer isso em outros projetos, já chama logo esse camarada esse PropsWithChildren acabou. VALEUUU!!!

2022-09-28 16:58 UTC, meycon1 commented on src/components/Markdown/index.tsx
> +import React, { ReactNode } from 'react';
Segue exemplo:

### React 18 - BREAKING CHANGE - Mudança do children

**Sem passagem de props**

**Before**
```
import React from 'react'; 
const Component: React.FC = ({children}) => {...}
```

**After**
```
import React from 'react';
export type ReactFCWithChildren = React.FC<PropsWithChildren>;
import {ReactFCWithChildren } from './react';
const Component: ReactFCWithChildren = ({children}) => {...}

```

**Com passagem de props**

**Before**
```
import React from 'react';
interface Props { ...}
const Component: React.FC<Props> = ({children}) => {...}
```

**After**
```
import React from 'react';
interface Props { ... }
const Component: React.FC<React.PropsWithChildren<Props>> = ({children}) => {...}
```
### Para mais informações do [React 18](https://reactjs.org/blog/2022/03/29/react-v18.html)

2022-09-28 17:00 UTC, lineubuilders commented on src/components/Markdown/index.tsx
> +import React, { ReactNode } from 'react';
Prontinho tropa, alterado!

2022-09-28 17:04 UTC, meycon1 approved these changes
Boa!! 👏👏👏

2022-09-29 21:36 UTC, fabinppkbuilders reviewed
Talvez a solução seja atualizar todas as dependencias da fluid também.
Provavelmente isso vai dar um pouco mais de dor de cabeça, maaaaaas com certeza vai agregar muito.

O que você pensa sobre isso @lineubuilders ?

@meycon1 vc chegou a testar essa versão do PR junto da atualização do react-native do outro PR?

2022-09-29 21:36 UTC, fabinppkbuilders commented on src/components/Markdown/index.tsx
>  import Markdown from 'react-native-markdown-display';
react-native-markdown-display precisa de atualização ou patch 💀 

![Captura de Tela 2022-09-29 às 18 32 50](https://user-images.githubusercontent.com/84453168/193146083-c3650a0d-dccf-46ba-9e7c-150844cc896c.png)

Se eu faço isso dentro da lib, funciona!

![Captura de Tela 2022-09-29 às 18 34 20](https://user-images.githubusercontent.com/84453168/193146310-ed87a5aa-3f6f-4961-9778-87c6920345ed.png)

2022-09-30 13:03 UTC, lineubuilders commented on src/components/Markdown/index.tsx
>  import Markdown from 'react-native-markdown-display';
Eu acho válido atualizar tudo. 

Mas conseguiria me detalhar quais vc gostaria que eu atualizasse? Assim tenho um ponto de partida melhor

2022-09-30 13:14 UTC, lineubuilders commented on src/components/Markdown/index.tsx
>  import Markdown from 'react-native-markdown-display';
E tbm não tive esse problema que vc apontou @fabinppkbuilders. Da uma olhada: 

![Screen Shot 2022-09-30 at 10 13 29](https://user-images.githubusercontent.com/91978378/193277623-f11e8668-8d05-490a-9b06-c347bd4cbb97.png)
![Screen Shot 2022-09-30 at 10 13 51](https://user-images.githubusercontent.com/91978378/193277629-c0dd78f8-ab2c-4993-bf02-339f61885a30.png)

2022-09-30 17:10 UTC, meycon1 commented on src/components/Markdown/index.tsx
>  import Markdown from 'react-native-markdown-display';
Por enquanto eu fiz um patche

2022-09-30 18:22 UTC, fabinppkbuilders commented on src/components/Markdown/index.tsx
>  import Markdown from 'react-native-markdown-display';
@lineubuilders seriam todas mesmo. Tudo kkkk
Com certeza isso vai gerar vários ajustes em todo lugar, mas dependendo, pode valer a pena. :thin
Acho que vale uma rápida tentativa. 👍 


@meycon1 este PR faz com que o patch não seja necessário.
Eu ainda não consegui validar se realmente o PR faz isso, se vc validar isso acredito que podemos mergear este PR.

2022-09-30 18:26 UTC, lineubuilders commented on src/components/Markdown/index.tsx
>  import Markdown from 'react-native-markdown-display';
@fabinppkbuilders show de bola então. Vou fazer isso mano!

2022-09-30 20:15 UTC, meycon1 commented on src/components/Markdown/index.tsx
>  import Markdown from 'react-native-markdown-display';
@fabinppkbuilders então eu estou tentando resolver uns problemas com a nova arquitetura vc não consegue fazer esse teste para nós fazendo o favor?

2022-09-30 21:10 UTC, fabinppkbuilders commented on src/components/Markdown/index.tsx
>  import Markdown from 'react-native-markdown-display';
@meycon1 sim, volu fazer também, só não consegui ainda.

Meus testes iniciais o patch não fez diferença 🤔 ...mas vou insistir ainda. 
Mantemos contato 👍

2022-10-11 13:52 UTC, fabinppkbuilders approved these changes
Por mim podemos mergear esse. Mais melhorias podem vir em próximos PRs.
O que acham?

2022-10-11 20:35 UTC, merged